name: Install Arachne with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-arachne:
    runs-on: ubuntu-latest

    steps:
    # Checkout the Arachne repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker
    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        sudo usermod -aG docker $USER
    
    - name: Verify Docker installation
      run: docker --version

    # Set up Docker Compose
    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Check Docker Compose version

    # Set up the environment (if necessary)
    - name: Set up environment
      run: |
        echo "Setting up environment variables..."
        # Add any environment variables here if needed (for example, for DB connections)
        # export MY_ENV_VAR=value
        echo "Environment setup complete."

    # Start Arachne using Docker Compose
    - name: Start Arachne with Docker Compose
      run: |
        cd install/docker
        docker-compose up -d  # Start the containers in detached mode

    # Optionally, verify the Arachne container is running
    - name: Verify Arachne is running
      run: |
        docker ps  # List running containers to ensure Arachne containers are up

    # Optional: Check if Arachne is accessible (assuming it exposes a web service)
    - name: Test Arachne installation
      run: |
        curl -s http://localhost:8080  # Replace with the correct port if needed
